### ISSUE TITLE
compilation roadblock on SotnApi.csproj line:11

### ISSUE THREAD

**Issue by siberpnk** [TalicZealot/SotnApi#2]
I noticed that **line:11** in **SotnApi.csproj** was preventing me from compiling due to the fact I didn't have a D: drive on my computer to output to. I just wanted to point this out in case anyone else was having problems compiling and as a way to suggest and edit to a generic solution.

**Comment by TalicZealot** [comment]
Oh thanks, I'm not sure why that doesn't use a relative path but it should. This repository is also quite outdated due to no interest.

**Comment by siberpnk** [comment]
I think people are always going to be more interested in the tools APIs create rather than the "pipe works". I think it's a great idea though.
